//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheet1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profiletbl
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Country { get; set; }
        public string Department { get; set; }
        public string Address { get; set; }
        public string Position { get; set; }
        public string Address2 { get; set; }
        public string Reports { get; set; }
        public decimal Postal { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public decimal Phone { get; set; }
        public Nullable<decimal> Phone2 { get; set; }
        public Nullable<decimal> Other { get; set; }
        public string PrimaryEmail { get; set; }
        public string SecondaryEmail { get; set; }
    }
}
