//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheet1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registertbl
    {
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public decimal Phonenumber { get; set; }
        public string Email { get; set; }
        public decimal Age { get; set; }
        public string gender { get; set; }
        public string Country { get; set; }
        public string SecurityQuestion1 { get; set; }
        public string SecurityAnswer1 { get; set; }
        public string SecurityQuestion2 { get; set; }
        public string SecurityAnswer2 { get; set; }
        public string SecurityQuestion3 { get; set; }
        public string SecurityAnswer3 { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    }
}
