//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheet1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Securitytbl
    {
        public string SecurityQuestions1 { get; set; }
        public string SecurityAnswer1 { get; set; }
        public string SecurityQuestions2 { get; set; }
        public string SecurityAnswer2 { get; set; }
        public string SecurityQuestions3 { get; set; }
        public string SecurityAnswer3 { get; set; }
    }
}
