//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheet1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Sunray12dbDataContext : DbContext
    {
        public Sunray12dbDataContext()
            : base("name=Sunray12dbDataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<newentrytbl> newentrytbls { get; set; }
        public virtual DbSet<NewTimeEntrytbl> NewTimeEntrytbls { get; set; }
        public virtual DbSet<newtimetbl> newtimetbls { get; set; }
        public virtual DbSet<Profiletbl> Profiletbls { get; set; }
        public virtual DbSet<Registertbl> Registertbls { get; set; }
        public virtual DbSet<Securitytbl> Securitytbls { get; set; }
        public virtual DbSet<tblauth> tblauths { get; set; }
        public virtual DbSet<tblChangePwd> tblChangePwds { get; set; }
        public virtual DbSet<tbllogin> tbllogins { get; set; }
    }
}
