//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheet1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChangePwd
    {
        public string Username { get; set; }
        public string CompanyId { get; set; }
        public string Linkedemail { get; set; }
        public string Password { get; set; }
    }
}
